id: P4454CC46
initial_creation_type: input
source_metadata:
  title: Dvayasaṃpattivārttika
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Śaiva
  data entry: Daniele Cuneo
  contribution to GRETIL: Daniele Cuneo
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:08:07.044576'
last_modified_at: '2022-03-09T15:08:07.044587'
